[[headers]]
  # Set Content-Type header for .jsx files
  for = "/*.jsx"
  [headers.values]
    access-control-allow-origin = "*"
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
