app = "lecturemonbackend2"
primary_region = "syd"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 0
processes = [ "app" ]

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tls_options]]
    alpn = ["http/1.1"]
    domains = ["api.lecturmo.org"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
